### ISSUE TITLE
Question: When will you make botnet system

### ISSUE THREAD

**Issue by lilcsz** [BOT-CODER/SniperMan#4]

**Comment by GuyPerson7018** [comment]
Lol, botnets are defined as a number of computers(typically in the thousands, largest known one is about 1 billion). You cannot "make" a botnet without a good worm that can infect computers rapidly. Therefore, you would require advanced programming knowledge(making flashy designs with python does not count, genius) as well as a zero day vulnerability to create a botnet system. So, if your programming knowledge has not improved by 100000000000000000000000000000 times since you made this "tool", you will not be able to make a botnet.

**Comment by lilcsz** [comment]
@GuyPerson7018 What about IoT Botnet with python?

**Comment by GuyPerson7018** [comment]
To make a botnet, you need remote access to multiple computers. That is typically done with worms that install backdoors in computers, which can be later accessed by hackers. You can make a botnet creator(typically a worm) with python, but you would need to make it able to automatically spread itself to other computers, which usually requires a zero day vulnerability. So while it is possible, I am 99.99999999999999% sure that the creator of this "tool" cannot make a botnet creator

**Comment by J0k3r-Squ4d** [comment]
> To make a botnet, you need remote access to multiple computers. That is typically done with worms that install backdoors in computers, which can be later accessed by hackers. You can make a botnet creator(typically a worm) with python, but you would need to make it able to automatically spread itself to other computers, which usually requires a zero day vulnerability. So while it is possible, I am 99.99999999999999% sure that the creator of this "tool" cannot make a botnet creator

Well considering he took [this repo](https://github.com/Ha3MrX/Ddos-Attack), converted it to python 3, took credit for it all, renamed it, and added a shitty menu- lol. His "tool" will never work anyway lol
